const EmojiDict = {
    "Normal": "🐕",
    "Fighting": "🥊",
    "Flying": "🦅",
    "Poison": "☠️",
    "Ground": "🌍",
    "Rock": "🗿",
    "Bug": "🐞",
    "Ghost": "👻",
    "Steel": "🔩",
    "Fire": "🔥",
    "Water": "💧",
    "Grass": "🌱",
    "Electric": "⚡️",
    "Psychic": "🔮",
    "Ice": "❄️",
    "Dragon": "🐉",
    "Dark": "🦇",
    "Fairy": "🧚‍♀️",
    "HP": "💖",
    "Attack": "⚔️",
    "Defense": "🛡️",
    "Sp. Attack": "💥",
    "Sp. Defense": "🦠",
    "Speed": "🏃"
}
 export default EmojiDict;